2024-09-12 19:25:21,464 root INFO Dividing 5 between 0
2024-09-12 19:25:21,464 root ERROR division by zero
Traceback (most recent call last):
  File "C:\Users\rod_e\OneDrive\Documentos\VSCODE\Automation Cookbook\Chapter Two\task_with_error_handling_step4.py", line 36, in <module>
    main(args.n1, args.n2, args.output)
  File "C:\Users\rod_e\OneDrive\Documentos\VSCODE\Automation Cookbook\Chapter Two\task_with_error_handling_step4.py", line 11, in main
    result = number / other_number
ZeroDivisionError: division by zero
